services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "9017:3333"
    environment:
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - DATABASE_URL=${DATABASE_URL}

  front:
    build:
      context: .
      dockerfile: apps/front/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_DEV=${VITE_DEV}
    ports:
      - "9018:3000"
    environment:
      - API_URL=${API_URL}
      - DATABASE_URL=${DATABASE_URL}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_DEV=${VITE_DEV}
