export default function Tower() {
    return (
        <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 32 32"
            className="w-2 h-2 text-black"
        >
            <path
                d="M26,17c3.9-3.9,3.9-10.1,0-14"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
            <path
                d="M22.7,13.3c1.8-1.8,1.8-4.9-0.2-6.8"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
            <path
                d="M6,3C2.1,6.9,2.1,13.1,6,17"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
            <path
                d="M9.3,6.7c-1.8,1.8-1.8,4.9,0.2,6.8"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
            <circle
                cx="16"
                cy="10"
                r="2"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
            <line
                x1="8"
                y1="29"
                x2="24"
                y2="29"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
            <line
                x1="13"
                y1="21"
                x2="19"
                y2="21"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
            <line
                x1="16.6"
                y1="12"
                x2="21"
                y2="29"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
            <line
                x1="11"
                y1="29"
                x2="15.4"
                y2="11.9"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinejoin="round"
                strokeMiterlimit="10"
            />
        </svg>
    );
}
