/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as privateProtectedRouteRouteImport } from './routes/(private)/_protected/route'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicSignUpRouteImport } from './routes/(public)/sign-up'
import { Route as privateProtectedDashboardRouteImport } from './routes/(private)/_protected/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateProtectedRouteRoute = privateProtectedRouteRouteImport.update({
  id: '/(private)/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/(public)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/(public)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const privateProtectedDashboardRoute =
  privateProtectedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privateProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/dashboard': typeof privateProtectedDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/dashboard': typeof privateProtectedDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(private)/_protected': typeof privateProtectedRouteRouteWithChildren
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(private)/_protected/dashboard': typeof privateProtectedDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/sign-up' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/sign-up' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(private)/_protected'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(private)/_protected/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  privateProtectedRouteRoute: typeof privateProtectedRouteRouteWithChildren
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_protected': {
      id: '/(private)/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_protected/dashboard': {
      id: '/(private)/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateProtectedDashboardRouteImport
      parentRoute: typeof privateProtectedRouteRoute
    }
  }
}

interface privateProtectedRouteRouteChildren {
  privateProtectedDashboardRoute: typeof privateProtectedDashboardRoute
}

const privateProtectedRouteRouteChildren: privateProtectedRouteRouteChildren = {
  privateProtectedDashboardRoute: privateProtectedDashboardRoute,
}

const privateProtectedRouteRouteWithChildren =
  privateProtectedRouteRoute._addFileChildren(
    privateProtectedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  privateProtectedRouteRoute: privateProtectedRouteRouteWithChildren,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
