# syntax=docker.io/docker/dockerfile:1

FROM oven/bun:latest AS base

WORKDIR /app

FROM base AS deps
COPY package.json bun.lock* ./
RUN bun install --no-save --frozen-lockfile
RUN bun install sharp

FROM base AS builder
WORKDIR /app

ARG BACKEND_URL
ENV BACKEND_URL=${BACKEND_URL}

ARG NEXT_INTERNAL_BACKEND_URL
ENV NEXT_INTERNAL_BACKEND_URL=${NEXT_INTERNAL_BACKEND_URL}

COPY --from=deps /app/node_modules ./node_modules
COPY src ./src
COPY public ./public
COPY next.config.mjs ./  
COPY tsconfig.json ./
COPY package.json ./
COPY tailwind.config.* postcss.config.mjs components.json ./
COPY types.d.ts ./
# COPY . .

RUN bun run build

# Install dependencies based on the preferred package manager

COPY src ./src
COPY public ./public
COPY next.config.mjs ./  
COPY tsconfig.json ./
COPY tailwind.config.* postcss.config.mjs components.json ./
COPY types.d.ts ./

# Environment variables must be present at build time
# https://github.com/vercel/next.js/discussions/14030
ARG NODE_ENV
ENV NODE_ENV="production"

# RUN bun run build

# Step 2. Production image, copy all the files and run next
FROM base AS runner

WORKDIR /app

# Don't run production as root
USER bun

# Automatically leverage output traces to reduce image size
COPY --from=builder --chown=bun:bun /app/public ./public
COPY --from=builder --chown=bun:bun /app/.next/standalone ./
COPY --from=builder --chown=bun:bun /app/.next/static ./.next/static

RUN mkdir -p .next/cache

# COPY --chown=bun:bun entrypoint.sh /usr/bin/entrypoint.sh
# RUN chmod +x /usr/bin/entrypoint.sh
# ENTRYPOINT ["entrypoint.sh"]

ENV NODE_ENV="production"
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

EXPOSE 3000

CMD ["bun", "./server.js"]
